import type { Repo } from "./types";
import { img } from "./images";

export const STATIC_PROJECTS: Repo[] = [
  {
    id: 999001,
    name: "DogWalk",
    description:
      "Encontre passeadores verificados perto de você e acompanhe o passeio do seu pet ao vivo, com GPS e pagamento por PIX. Marketplace completo com autenticação, Stripe e geolocalização em tempo real.",
    html_url: "",
    homepage: "https://seu.pet",
    stargazers_count: 0,
    forks_count: 0,
    language: "TypeScript",
    topics: ["featured", "web", "marketplace"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    hasDemo: true,
    imageUrl: img("/projects/seu.pet.webp"),
    videoUrl: "/projects/seu-pet-scroll.mp4",
  },

  {
    id: 999002,
    name: "Arachne",
    description:
      "Da página web à resposta: captura conteúdo de qualquer site, extrai dados de 44+ formatos de documento e conversa com o conhecimento via RAG semântico. MCP server + crawl4ai, com busca híbrida web e vetorial.",
    html_url: "https://github.com/Samuelfmedeiros/arachne-mcp",
    homepage: "https://arachne.seu.pet",
    stargazers_count: 1,
    forks_count: 0,
    language: "Python",
    topics: ["featured", "web", "ai", "data", "fastapi", "python", "mcp", "crawl4ai", "rag", "browser-automation", "vision"],
    pushed_at: "2026-08-11T22:06:39Z",
    created_at: "2026-08-11T22:06:39Z",
    imageGradient: "linear-gradient(135deg, #0d1117 0%, #1a1a2e 50%, #16213e 100%)",
    hasDemo: true,
    imageUrl: img("/projects/arachne.webp"),
  },

  {
    id: 999003,
    name: "Portifolio",
    description:
      "Este site, em estilo cockpit sci-fi — Next.js, Framer Motion e animações cinematográficas. Modo claro/escuro, 6 paletas de cores, PT/EN e atenção total a mobile, acessibilidade e performance.",
    html_url: "https://github.com/Samuelfmedeiros/Portifolio",
    homepage: "https://samuelmedeiros.vercel.app",
    stargazers_count: 0,
    forks_count: 0,
    language: "TypeScript",
    topics: ["featured", "web"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    hasDemo: true,
    imageUrl: img("/projects/portifolio.webp"),
  },
  {
    id: 999004,
    name: "lifelog",
    description:
      "Blog pessoal onde compartilho aprendizados reais de engenharia — otimização de performance, refatorações, dashboards e bastidores dos meus projetos. Astro, MDX, TypeScript e design system próprio.",
    html_url: "https://github.com/Samuelfmedeiros/lifelog",
    homepage: "https://lifelog-sepia.vercel.app",
    stargazers_count: 0,
    forks_count: 0,
    language: "TypeScript",
    topics: ["featured", "web", "blog", "astro", "mdx"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0d1117 0%, #1a1a2e 50%, #16213e 100%)",
    hasDemo: true,
    imageUrl: img("/projects/lifelog.webp"),
  },
  // Games — ordem definida pelo Samuel: memory-matrix → simon-game → code-typing → terminal → asteroid-dodge
  {
    id: 1001,
    name: "memory-matrix",
    description:
      "Jogo de memória visual. Memorize as células destacadas e recrie o padrão!",
    html_url: "https://github.com/Samuelfmedeiros/memory-matrix",
    homepage: "/games/memory-matrix/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0d1117 0%, #161b22 50%, #21262d 100%)",
    hasDemo: false,
    imageUrl: img("/projects/memory-matrix.webp"),
  },
  {
    id: 1002,
    name: "simon-game",
    description:
      "Jogo clássico de memorização de sequência de cores. Repita a sequência para pontuar!",
    html_url: "https://github.com/Samuelfmedeiros/simon-game",
    homepage: "/games/simon-game/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    hasDemo: false,
    imageUrl: img("/projects/simon-game.webp"),
  },
  {
    id: 1003,
    name: "code-typing",
    description:
      "Desafio de digitação de código. Digite snippets de várias linguagens o mais rápido possível!",
    html_url: "https://github.com/Samuelfmedeiros/code-typing",
    homepage: "/games/code-typing/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    hasDemo: false,
    imageUrl: img("/projects/code-typing.webp"),
  },
  {
    id: 1004,
    name: "terminal",
    description:
      "Terminal interativo estilo shell — navegue pelo portfólio com comandos, easter eggs e temas retrô.",
    html_url: "https://github.com/Samuelfmedeiros/terminal",
    homepage: "/games/terminal/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "TypeScript",
    topics: ["game", "react", "terminal"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 50%, #16213e 100%)",
    hasDemo: false,
    imageUrl: img("/projects/terminal.webp"),
  },
  {
    id: 1005,
    name: "asteroid-dodge",
    description:
      "Jogo de desviar de asteroides. Controle a nave com o mouse e sobreviva o máximo possível!",
    html_url: "https://github.com/Samuelfmedeiros/asteroid-dodge",
    homepage: "/games/asteroid-dodge/index.html",
    stargazers_count: 0,
    forks_count: 0,
    language: "JavaScript",
    topics: ["game", "react"],
    pushed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    imageGradient: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    hasDemo: false,
    imageUrl: img("/projects/asteroid-dodge.webp"),
  },
];

export const FEATURED_PROJECTS = [
  "DogWalk",
  "Arachne",
  "Portifolio",
  "lifelog",
  "memory-matrix",
  "simon-game",
  "code-typing",
  "terminal",
  "asteroid-dodge",
];
export const GAME_PROJECTS = ["memory-matrix", "simon-game", "code-typing", "terminal", "asteroid-dodge"];
